services:
  api:
    build: .
    container_name: olist-dashboard
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./dataset:/app/dataset
      - ./models:/app/models
